//! Stage 1: deterministic candidate-file selection.
//!
//! The walk visits every directory the exclusion rules allow and keeps files
//! that look like handwritten source code: a known code extension, no
//! generated-file naming pattern, and a size below the configured limit.
//! Generated content that can only be recognized by reading the file (header
//! markers, minified single-line bundles) is filtered later, at scan time.

use access::{Accessor, FileType};
use serde::Serialize;

use crate::{Error, SelectionConfig};

/// File extensions treated as source code by default.
pub(crate) const DEFAULT_EXTENSIONS: &[&str] = &[
    "bash", "c", "cc", "cjs", "clj", "cljc", "cljs", "cpp", "cs", "cxx", "d", "dart", "elm", "erl",
    "ex", "exs", "fish", "go", "groovy", "h", "hh", "hpp", "hrl", "hs", "hxx", "java", "jl", "js",
    "jsx", "kt", "kts", "lua", "m", "mjs", "ml", "mli", "mm", "nim", "php", "pl", "pm", "ps1",
    "purs", "py", "r", "rb", "rkt", "rs", "scala", "sh", "sql", "svelte", "swift", "tcl", "ts",
    "tsx", "vue", "zig", "zsh",
];

/// Directory names pruned from the walk by default. Hidden directories
/// (names starting with `.`) are always pruned.
pub(crate) const EXCLUDED_DIRECTORIES: &[&str] = &[
    "bower_components",
    "build",
    "deps",
    "dist",
    "external",
    "generated",
    "node_modules",
    "obj",
    "out",
    "pods",
    "target",
    "third-party",
    "third_party",
    "thirdparty",
    "vendor",
    "vendored",
    "venv",
    "__pycache__",
];

/// File-name suffixes produced by code generators and bundlers.
const GENERATED_FILE_SUFFIXES: &[&str] = &[
    ".bundle.js",
    ".designer.cs",
    ".freezed.dart",
    ".g.cs",
    ".g.dart",
    ".gen.go",
    ".gen.ts",
    ".generated.cs",
    ".min.css",
    ".min.js",
    ".pb.cc",
    ".pb.go",
    ".pb.h",
    ".pb.swift",
    "_generated.go",
    "_pb.js",
    "_pb.ts",
    "_pb2.py",
    "_pb2_grpc.py",
];

/// Lowercase markers that identify generated files when found in the header.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "auto-generated file",
    "autogenerated file",
    "automatically generated",
    "code generated by",
    "do not edit",
    "generated automatically",
    "this file is generated",
    "this file was generated",
];

/// How many leading characters of a file are inspected for generated markers.
const HEADER_CHARS: usize = 4096;

/// A file that survived stage 1 and may be sampled in stage 2.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct Candidate {
    pub path: String,
}

/// Counters describing what the stage-1 walk saw and why files were dropped.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize)]
pub struct SelectionStats {
    /// Files encountered during the walk, selected or not.
    pub files_seen: usize,
    /// Files that survived every stage-1 filter.
    pub files_selected: usize,
    /// Files dropped because their extension is not in the allowlist.
    pub files_skipped_extension: usize,
    /// Files dropped by name: hidden files and generated-file suffixes.
    pub files_skipped_pattern: usize,
    /// Files dropped because they exceed `max_file_bytes`.
    pub files_skipped_too_large: usize,
    /// Directories pruned by the exclusion rules (their contents were never listed).
    pub directories_pruned: usize,
    /// Directories that could not be listed.
    pub directories_errored: usize,
    /// True when the walk stopped early because `max_files` candidates were found.
    pub truncated: bool,
}

/// Walk the repository and return the candidate files with selection counters.
///
/// Only a failure to list the repository root is fatal; unreadable
/// subdirectories are counted and skipped.
pub(crate) fn select_files<A>(
    accessor: &A,
    config: &SelectionConfig,
) -> Result<(Vec<Candidate>, SelectionStats), Error>
where
    A: Accessor + ?Sized,
{
    let mut stats = SelectionStats::default();
    let mut candidates = Vec::new();
    let mut pending = vec![String::from(".")];

    while let Some(directory) = pending.pop() {
        let entries = match accessor.list_dir(&directory) {
            Ok(entries) => entries,
            Err(error) if directory == "." => return Err(error.into()),
            Err(_) => {
                stats.directories_errored += 1;
                continue;
            }
        };

        for entry in entries {
            let path = if directory == "." {
                entry.name.clone()
            } else {
                format!("{directory}/{}", entry.name)
            };
            match entry.entry_type {
                FileType::Directory => {
                    if is_excluded_directory(&entry.name, config) {
                        stats.directories_pruned += 1;
                    } else {
                        pending.push(path);
                    }
                }
                FileType::File => {
                    stats.files_seen += 1;
                    if !has_code_extension(&entry.name, config) {
                        stats.files_skipped_extension += 1;
                    } else if has_generated_name(&entry.name) {
                        stats.files_skipped_pattern += 1;
                    } else if entry.size.is_some_and(|size| size > config.max_file_bytes) {
                        stats.files_skipped_too_large += 1;
                    } else {
                        candidates.push(Candidate { path });
                        if candidates.len() >= config.max_files {
                            stats.truncated = true;
                            stats.files_selected = candidates.len();
                            return Ok((candidates, stats));
                        }
                    }
                }
            }
        }
    }

    stats.files_selected = candidates.len();
    Ok((candidates, stats))
}

fn has_code_extension(name: &str, config: &SelectionConfig) -> bool {
    let Some((stem, extension)) = name.rsplit_once('.') else {
        return false;
    };
    if stem.is_empty() {
        return false;
    }
    let extension = extension.to_ascii_lowercase();
    config.extensions.contains(&extension)
}

fn is_excluded_directory(name: &str, config: &SelectionConfig) -> bool {
    if name.starts_with('.') {
        return true;
    }
    let name = name.to_ascii_lowercase();
    config.excluded_directories.contains(&name)
}

fn has_generated_name(name: &str) -> bool {
    if name.starts_with('.') {
        return true;
    }
    let name = name.to_ascii_lowercase();
    GENERATED_FILE_SUFFIXES
        .iter()
        .any(|suffix| name.ends_with(suffix))
}

/// Detect generated or minified content from the beginning of a file.
pub(crate) fn looks_generated(content: &str) -> bool {
    let header: String = content.chars().take(HEADER_CHARS).collect();
    // A header-sized prefix without a single newline is minified or packed.
    if header.len() < content.len() && !header.contains('\n') {
        return true;
    }
    let header = header.to_lowercase();
    GENERATED_MARKERS
        .iter()
        .any(|marker| header.contains(marker))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testing::MapAccessor;

    fn config() -> SelectionConfig {
        SelectionConfig {
            max_file_bytes: 64,
            ..SelectionConfig::default()
        }
    }

    #[test]
    fn walk_selects_code_and_skips_vendored_generated_and_large_files() {
        let accessor = MapAccessor::new([
            ("src/main.rs", "fn main() {}\n"),
            ("src/lib.rs", "pub fn add() {}\n"),
            ("README.md", "docs\n"),
            (".hidden/secret.rs", "fn hidden() {}\n"),
            (".config.js", "module.exports = {};\n"),
            ("node_modules/pkg/index.js", "vendored\n"),
            ("vendor/lib.go", "vendored\n"),
            ("proto/service_pb2.py", "generated\n"),
            ("web/app.min.js", "minified\n"),
            ("data/huge.py", &"x = 1\n".repeat(100)),
        ]);

        let (candidates, stats) = select_files(&accessor, &config()).unwrap();
        let mut paths: Vec<&str> = candidates
            .iter()
            .map(|candidate| candidate.path.as_str())
            .collect();
        paths.sort_unstable();

        assert_eq!(paths, ["src/lib.rs", "src/main.rs"]);
        assert_eq!(stats.files_selected, 2);
        assert_eq!(stats.files_skipped_extension, 1); // README.md
        assert_eq!(stats.files_skipped_pattern, 3); // .config.js, service_pb2.py, app.min.js
        assert_eq!(stats.files_skipped_too_large, 1); // data/huge.py
        assert_eq!(stats.directories_pruned, 3); // .hidden, node_modules, vendor
        assert_eq!(stats.files_seen, 7); // everything outside pruned directories
        assert!(!stats.truncated);
    }

    #[test]
    fn walk_stops_at_the_candidate_cap() {
        let accessor = MapAccessor::new([
            ("a.rs", "fn a() {}\n"),
            ("b.rs", "fn b() {}\n"),
            ("c.rs", "fn c() {}\n"),
        ]);
        let config = SelectionConfig {
            max_files: 2,
            ..SelectionConfig::default()
        };

        let (candidates, stats) = select_files(&accessor, &config).unwrap();
        assert_eq!(candidates.len(), 2);
        assert!(stats.truncated);
    }

    #[test]
    fn generated_headers_and_minified_content_are_detected() {
        assert!(looks_generated(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\n"
        ));
        assert!(looks_generated("/* @generated */\nmodule.exports = {};\n"));
        assert!(looks_generated(&"x".repeat(HEADER_CHARS * 2)));
        assert!(!looks_generated("fn main() {\n    println!(\"hi\");\n}\n"));
        // A short single-line file is not minified.
        assert!(!looks_generated("const A = 1;"));
    }
}
